### ISSUE TITLE
[Bug]“framework/il2cpp-init.h”: No such file or directory

### ISSUE THREAD

**Issue by ancon** [Korepi/Korepi#1]
## Bug

Please enter a clear and accurate description of this bug here.

##  How to reproduce this bug

Steps to reproduce this bug:
1. Clone repository with `git clone --recurse-submodules https://github.com/Korepi/Korepi.git`
2. Open korepi.sln
3. Build solution  korepi.sln

## Expectation

Give a brief description of what you expect.
link this:
![image](https://github.com/Korepi/Korepi/assets/6762451/507c8437-7793-4ade-b4b7-e74dda6b901f)

## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.
![image](https://github.com/Korepi/Korepi/assets/6762451/dcd1a0b1-7073-45f9-b929-2465a0e595bc)

## Your device information
 
 - System information:
 
 - Version:
Windows 10 pro 22h2

## Additional information

You can enter additional information about this bug here.
I just want to learn how to build, thanks

**Comment by tedddeptrai** [comment]
this source on this page is outdated, probably author won't share anything. so goodluck

**Comment by Xcating** [comment]
halo

**Comment by Xcating** [comment]
offsets得你自己更新噢

**Comment by Failzuma** [comment]
i would say dont do something skill issued 😆

**Comment by ancon** [comment]
> offsets得你自己更新噢

怎么更新呢？

**Comment by Strigger7** [comment]
those files are not public
