### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by AkulaTim** [Korepi/Korepi#11]
В чем может быть проблема ????

into GetLocalDNSs proc.
[Debug] [ProtectionBypass.cpp:127] ReportLuaShellResult: GameAnalyticsData, {"1":["3.6.0"],"0":[3]}
[Debug] [ProtectionBypass.cpp:138] Letting the first LuaShellResult pass, blocking the rest.
[Debug] [ProtectionBypass.cpp:127] ReportLuaShellResult: GameAnalyticsData, {"107":["GenshinImpact_Data"]}
[Debug] [ProtectionBypass.cpp:127] ReportLuaShellResult: GameAnalyticsData, {"106":["mhypbase.dll","UnityPlayer.dll","GenshinImpact.exe","HoYoKProtect.sys","mhyprot3.Sys","GenshinImpact_Data\Native\UserAssembly.dll","GenshinImpact_Data\Plugins\Astrolabe.dll","GenshinImpact_Data\Plugins\chrome_elf.dll","GenshinImpact_Data\Plugins\cri_mana_vpx.dll","GenshinImpact_Data\Plugins\cri_vip_unity_pc.dll","GenshinImpact_Data\Plugins\cri_ware_unity.dll","GenshinImpact_Data\Plugins\d3dcompiler_47.dll","GenshinImpact_Data\Plugins\hdiffz.dll","GenshinImpact_Data\Plugins\hpatchz.dll","GenshinImpact_Data\Plugins\kcp.dll","GenshinImpact_Data\Plugins\libEGL.dll","GenshinImpact_Data\Plugins\libGLESv2.dll","GenshinImpact_Data\Plugins\libUbiCustomEvent.dll","GenshinImpact_Data\Plugins\mailbox.dll","GenshinImpact_Data\Plugins\MiHoYoMTRSDK.dll","GenshinImpact_Data\Plugins\mihoyonet.dll","GenshinImpact_Data\Plugins\MiHoYoSDKUploader.dll","GenshinImpact_Data\Plugins\Mmoron.dll","GenshinImpact_Data\Plugins\MTBenchmark_Windows.dll","GenshinImpact_Data\Plugins\NamedPipeClient.dll","GenshinImpact_Data\Plugins\Rewired_DirectInput.dll","GenshinImpact_Data\Plugins\Telemetry.dll","GenshinImpact_Data\Plugins\UnityNativeChromaSDK.dll","GenshinImpact_Data\Plugins\UnityNativeChromaSDK3.dll","GenshinImpact_Data\Plugins\vk_swiftshader.dll","GenshinImpact_Data\Plugins\vulkan-1.dll","GenshinImpact_Data\Plugins\xlua.dll","GenshinImpact_Data\Plugins\ZFEmbedWeb.dll","GenshinImpact_Data\Plugins\ZFProxyWeb.dll","GenshinImpact_Data\Plugins\zf_cef.dll","GenshinImpact_Data\blueReporter.exe","GenshinImpact_Data\upload_crash.exe","GenshinImpact_Data\Plugins\crashreport.exe","GenshinImpact_Data\Plugins\ZFGameBrowser.exe"]}

**Comment by Strigger7** [comment]
it's normal, that means the tool is working properly
