### ISSUE TITLE
[Help] Korepi Discord Invitation Link Invalid/Expired

### ISSUE THREAD

**Issue by 21anakonda21** [Korepi/Korepi#113]
## Can't join the korepi discord server.

 The korepi invitation link on the catalog doesn't work. I tried copy and paste or click the link directly. Nothing worked. I tried the discord phone app, windows app and website, none of them worked.

## How to reproduce this problem

Steps to reproduce this issue:
1. Go to korepi catalog on GitHub.
2. Go to "joining the server" tab.
3. Click the "invitation link" in step 3.

## Screenshot/Video

![image](https://github.com/user-attachments/assets/cc705251-1d02-4497-a706-2142ba6b9f30)

## Device information
 
 - System information: Windows 11 Home 64-bit
 
 - Version: 23H2

**Comment by cryo1309** [comment]
can i have new discord invitation link because the link in the catalog is expired
