### ISSUE TITLE
[Help] 3.7version can't work

### ISSUE THREAD

**Issue by Deeperfinder** [Korepi/Korepi#14]
[02:46:50] [Info] [il2cpp-init.cpp:192] Failed to detect version: CNRELWin3.6.0.
[02:46:50] [Info] [il2cpp-init.cpp:192] Failed to detect version: OSRELWin3.6.0.

**Comment by MMALI3287** [comment]
3.7 version just released. I guess developers will need time to build a new release

**Comment by dagongzhanshi** [comment]
大概什么时候可以更新呢

**Comment by 2054469641** [comment]
更新啊，能不能加防检测啊

**Comment by cyolc932** [comment]
> 更新啊，能不能加防检测啊

注意措辞
免费的别太高期望

**Comment by 2054469641** [comment]
> 

主要是mhy更新了新的ACE检测

**Comment by dagongzhanshi** [comment]
我只开剧情加速容易被封吗

**Comment by Zyc0101** [comment]
按F1无效果

**Comment by Ira125** [comment]
[Debug] [main.cpp:69] UserAssembly.dll isn't initialized, waiting for 2 sec.
[Debug] [main.cpp:69] UserAssembly.dll isn't initialized, waiting for 2 sec.
[Debug] [main.cpp:69] UserAssembly.dll isn't initialized, waiting for 2 sec.
[Debug] [main.cpp:82] Waiting 20.000 sec for game to initialize.
(If Genshin crashes after this line you might want to try longer delay in cfg.ini)
[Debug] [PatternScanner.cpp:248] Module D:\Genshin Impact\Genshin Impact Game\UnityPlayer.dll bound 0x00007FFD64100000-0x00007FFD664C6000.
url fetch responce: {"retcode":0,"message":"success","data":null}
[Debug] [PatternScanner.cpp:248] Module D:\Genshin Impact\Genshin Impact Game\YuanShen_Data\Native\UserAssembly.dll bound 0x00007FFD4E2B0000-0x00007FFD5EAA2000.
url fetch responce: {"retcode":0,"message":"success","data":null}
[Info] [il2cpp-init.cpp:226] Detected version: CNRELWin3.7.0.
[Debug] [ProtectionBypass.cpp:46] Sniffed correct signature for type 0 value '9f3d635bc7747c5ec76c97afe6069447'
[Debug] [ProtectionBypass.cpp:46] Sniffed correct signature for type 1 value '94d8337cb4e45b3fc514163b1a93cd2426'
[Debug] [ProtectionBypass.cpp:46] Sniffed correct signature for type 3 value '170017649'
[Debug] [ProtectionBypass.cpp:94] Initialized
[Debug] [renderer.cpp:209] Initialize IMGui...
[Debug] [dx11-hook.cpp:113] Initializing D3D11 hook: started.
[Debug] [dx11-hook.cpp:120] SwapChain Present: 00007FFE2C913900
[Debug] [dx11-hook.cpp:123] Initializing D3D11 hook: done.
[Debug] [main.cpp:107] Config path is at D:\Genshin Impact\cfg.json
[Debug] [renderer.cpp:490] ImGUI: DirectX11 backend initialized successfully.
url fetch responce: {"retcode":0,"message":"success","data":null}
then the game crashed

**Comment by dagongzhanshi** [comment]
为什么用一小会后容易崩溃卡退？（按insert）打开GUI界面
