### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by CHINA-HACK** [Korepi/Korepi#16]
## Bug

Please enter a clear and accurate description of this bug here.
在注入之后刷屏报错，报错代码为Exception: EXCEPTION_ACCESS_VIOLATION; Code: 0xc0000005; Source: GameManager_Update_Hook
##  How to reproduce this bug

Steps to reproduce this bug:
1. 注入
2. 启用 屏蔽Mhyprot2句柄
3. 启用 关闭验证
4. 启用与反作弊绕过有关的功能（似乎功能除外）

## Expectation

Give a brief description of what you expect.

## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.

## Your device information
 
 - System information:
 
 - Version:
ZH_cn 0.7.0 genshin3.7
## Additional information

You can enter additional information about this bug here.

**Comment by GameTianxiuDragon** [comment]
[22:47:00] [Error] [il2cpp-init.cpp:268] CN client is not supported.
