### ISSUE TITLE
[Help]最新版本游戏进门会崩溃

### ISSUE THREAD

**Issue by Oc8369** [Korepi/Korepi#19]
使用injector打开游戏，进门后会崩溃，调整cfg.ini中的延迟至更长也无法解决

**Comment by xiaocheng168** [comment]
相同问题 China Server

**Comment by CHINA-HACK** [comment]
关掉所有和反作弊有关的项目就好

**Comment by zhongshij** [comment]
我也是

**Comment by 844814048** [comment]
国服进不去

**Comment by dagongzhanshi** [comment]
有的人使用是正常的，也没调cfg.ini的延迟，不知道是什么原因

**Comment by huanhuachenfeng** [comment]
FFF -  China Server：Flash back at the last second of loading.

**Comment by huanhuachenfeng** [comment]
FFF -  China Server：Flash back at the last second of loading.

**Comment by Origin0915** [comment]
还需要自己找个过检测吗？各位

**Comment by beuzhi** [comment]
When will Chinese servers be supported?

**Comment by huanhuachenfeng** [comment]
The solution：cfg.ini -- InitializationDelayMS = 0

**Comment by huanhuachenfeng** [comment]
> When will Chinese servers be supported?何时支持中文服务器？

In a few days

**Comment by Origin0915** [comment]
> > When will Chinese servers be supported?何时支持中文服务器？
> 
> In a few days

thanks

**Comment by hdz692** [comment]
cfg.ini初始化延迟改成60000能解决

**Comment by hdz692** [comment]
> cfg.ini初始化延迟改成60000能解决

cfg .ini initialization delay can be solved by changing it to 60000

**Comment by Origin0915** [comment]
> cfg.ini初始化延迟改成60000能解决

是不是还没支持国服呢？

**Comment by Origin0915** [comment]
> > cfg.ini初始化延迟改成60000能解决
> 
> 是不是还没支持国服呢？

CN client is not supported.

**Comment by xiaocheng168** [comment]
到现在这个最新版 [P2](https://github.com/Korepi/keyauth-cpp-library/releases/tag/P2)

**Comment by Oc8369** [comment]
国服未适配

**Comment by GameTianxiuDragon** [comment]
[22:47:00] [Error] [il2cpp-init.cpp:268] CN client is not supported.
