### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by Rinacchi01** [Korepi/Korepi#31]
Hello, i wanted to join the discord, but the link isnt working...can you maybe link it new here?

**Comment by BratikAI** [comment]
Do you have patreon? I could support you and get on the discord.

**Comment by QweRezOn** [comment]
> Do you have patreon? I could support you and get on the discord.


I'm not a developer, I'm just a translator, I don't have such rights

**Comment by Ross0907** [comment]
currently its version 4.1 any info on when the server might open for free version ?
