### ISSUE TITLE
[Help] download

### ISSUE THREAD

**Issue by Matix759** [Korepi/Korepi#38]
how to download the latest version?

**Comment by 123jhkn** [comment]
who can upload a current CN vversion

**Comment by Abdulla4Gamer** [comment]
go to https://github.com/Korepi/keyauth-cpp-library then go to releases.

**Comment by 123jhkn** [comment]
is not for cn bro

**Comment by KhrystenkoSergey** [comment]
I'm sorry that I'm not writing to the channel for this. but I would like to access the discord server and I can't find the actual link anywhere

**Comment by OIWWIO** [comment]
where is the Interactive map, it will not be there?

**Comment by QweRezOn** [comment]
> where is the Interactive map, it will not be there?
Hello, if I'm not mistaken, this feature is not available in the P version.

**Comment by HyunJae5463** [comment]
Is there any version that has the Map feature? Willing to pay for it too if its not more than $15 a month

**Comment by QweRezOn** [comment]
> Is there any version that has the Map feature? Willing to pay for it too if its not more than $15 a month


The map is available in version F (fans), to get this version, you need to be on the discord server.

At the moment, the server is closed, and there have been no updates for the latest version yet

**Comment by HyunJae5463** [comment]
> > Is there any version that has the Map feature? Willing to pay for it too if its not more than $15 a month
> 
> The map is available in version F (fans), to get this version, you need to be on the discord server.
> 
> At the moment, the server is closed, and there have been no updates for the latest version yet

Sad, is there still any chance to get an invite to the server? Id really like to pay for it.
