### ISSUE TITLE
[Help] There is no teleport tab in the cheat

### ISSUE THREAD

**Issue by taetcon** [Korepi/Korepi#39]
![image](https://github.com/Korepi/Korepi/assets/136772147/68f27ad8-c1ca-41ae-88d1-c48fef027948)

**Comment by ebayybe** [comment]
In the new version, the teleport was cut out. The paid features have

**Comment by ebayybe** [comment]
The feature has been removed from the free version. It seems to be in the paid one

**Comment by QweRezOn** [comment]
Hello, this feature has been removed in the P version.
