### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by sudakalemontea1** [Korepi/Korepi#40]
## Describe the problem

Please fill in here a clear and accurate description of the problem you are experiencing.

## How to reproduce this problem

Steps to reproduce this issue:
打开injector

## Help you need
进去就闪退，软件报错

## Screenshot/Video
![QQ截图20230704153012](https://github.com/Korepi/Korepi/assets/138564277/73084b7f-25ba-4336-b526-99de8045552c)

## Your device information
 Additional information

Here you can enter additional information about the help you need.

**Comment by tedddeptrai** [comment]
F version cannot be opened in Chinese Genshin server

**Comment by sudakalemontea1** [comment]
P ？What is "P"？

**Comment by sudakalemontea1** [comment]
> P version cannot be opened in Chinese Genshin server

P ？What is "P"？

**Comment by iiTzMYUNG** [comment]
Because of the New 2.8 Ver. Update I think showing me the same error maybe wait for the update???

**Comment by Dino9xVN** [comment]
Phiên bản mới đã được cập nhật và không thể sử dụng nữa !

**Comment by HyunJae5463** [comment]
Anyone that is in the Discord has an update? Will next version come out? Or as often times before just abandoned?

**Comment by QweRezOn** [comment]
> Anyone that is in the Discord has an update? Will next version come out? Or as often times before just abandoned?



The update is already available via the link [Тык](https://github.com/Korepi/keyauth-cpp-library/releases)
