### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by ZiggMVP** [Korepi/Korepi#42]
I understand that, you already tired of such questions, but I would like to know if Chita is planned to be supported in the genshin 3.8 version or not?

**Comment by ZiggMVP** [comment]
"on the off-chance" I don't ask when it will be done.  I ask if it's worth the wait

**Comment by QweRezOn** [comment]
I passed your question to one of the developers, and he gave this answer:

_currently, Public version is not support for CNRel, if ppl in CN server want to use Korepi, they must be Fans in discord and use Fan's version_

**Comment by QweRezOn** [comment]
> Thanks for the very prompt response to this question.  can I ask you for a link to this Discord server



I can provide you with a link, but you probably won't be able to join it because it's closed and doesn't open often.

discord.gg/cottonbuds
