### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by AntyWar** [Korepi/Korepi#45]
The 3.8 Version is asking me for LICENSE KEY like how to get it?

**Comment by QweRezOn** [comment]
Hello, you can find the link below

https://github.com/Korepi/Korepi-Tutorial

If there are no more questions, please close the Issue

**Comment by smzga** [comment]
When will the channel open?

**Comment by QweRezOn** [comment]
> When will the channel open?


Hi, we don't have this information
