### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by Tipswww** [Korepi/Korepi#46]
我无法加入到Discord服务器中，它显示服务器已关闭，可以给个开启时间方便加入吗？

I can't join the Discord server, it shows that the server is down, can I give it an open time to join?

Я не могу присоединиться к серверу Discord, он показывает, что сервер не работает, могу ли я дать ему открытое время для присоединения?

Thank you ！

**Comment by QweRezOn** [comment]
Hello, it was not necessary to duplicate in several languages, but thank you.

Access to the discord server is closed, and it is unknown when it will be opened, I can only advise you to monitor the relevance of the link, and if you are lucky, you will be able to get to the server.

[link discord](https://discord.gg/cottonbuds)
