### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by SafwanWilson** [Korepi/Korepi#48]
Hello i cant join discord is there anyproblem with it ?

**Comment by WhisperingTelamonster** [comment]
Its closed only devs

**Comment by QweRezOn** [comment]
Hello, access to the Discord server is closed, keep an eye on the relevance of the link, you may be able to log in
https://discord.gg/cottonbuds

If there are no more questions, please close the topic.

**Comment by SafwanWilson** [comment]
okay thank you
