### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by Vocaese** [Korepi/Korepi#50]
请问中国服务器什么时候开放Discord验证

**Comment by QweRezOn** [comment]
> 请问中国服务器什么时候开放Discord验证
Cnina version.


我使用在线翻译，因为我不会说中文。

您好，如果您正在询问打开Discord服务器，那么它是未知的，它是关闭的，没有人知道它什么时候会打开。

如果你还有问题，写，如果没有问题，请关闭主题。


English version.


Hello, if you asked about opening the Discord server, then we do not know, it is closed, and no one knows when it will open.

If you still have questions, write, if there are no problems, please close the topic.

**Comment by Vocaese** [comment]
thanks
