### ISSUE TITLE
[Help]When will version 4.0 be implemented?

### ISSUE THREAD

**Issue by Snow1st** [Korepi/Korepi#62]
バージョン4.0に対応しているkorepiはどこで公開されますか？
Where will the korepi that supports version 4.0 be published?
버전 4.0을 지원하는 콜레피는 어디에서 공개됩니까?
Где опубликован корепи, поддерживающий версию 4.0?

**Comment by QweRezOn** [comment]
Здравствуйте, следите за новостями на нашем дискорд сервере, или ожидайте новостей на GitHub

**Comment by yashpirx** [comment]
> Здравствуйте, следите за новостями на нашем дискорд сервере, или ожидайте новостей на GitHub

а когда можно будет зайти на дс сервер? он закрыт, я уже 3 неделю пытаюсь

**Comment by ET3RO** [comment]
> > Здравствуйте, следите за новостями на нашем дискорд сервере, или ожидайте новостей на GitHub
> 
> а когда можно будет зайти на дс сервер? он закрыт, я уже 3 неделю пытаюсь

Тот же вопрос дружище

**Comment by shafeeq40** [comment]
дискорд сервер закрыт и я не открою его я думаю

**Comment by iHoang** [comment]
4.0 doesn't work

**Comment by QweRezOn** [comment]
> > Здравствуйте, следите за новостями на нашем дискорд сервере, или ожидайте новостей на GitHub
> 
> а когда можно будет зайти на дс сервер? он закрыт, я уже 3 неделю пытаюсь


Когда-нибудь он будет открыт... по крайне мере нужно в это верить...

**Comment by f1den** [comment]
> > > Здравствуйте, следите за новостями на нашем дискорд сервере, или ожидайте новостей на GitHub
> > 
> > 
> > а когда можно будет зайти на дс сервер? он закрыт, я уже 3 неделю пытаюсь
> 
> Когда-нибудь он будет открыт... по крайне мере нужно в это верить...

я считаю что нужно его открыть на 10 минут прямо сейчас, чтобы я зашёл :D
