### ISSUE TITLE
Будет ли доступна korepi для геншина 4.0 в периоде с 23-25 августа?

### ISSUE THREAD

**Issue by EWENTOL** [Korepi/Korepi#65]
Я думаю, разработчики korepi уже стараются и пишут код для адаптации под версию 4.0. Сейчас вышла новая локация, поэтому думаю, что для обновления korepi понадобится как минимум 10-13 дней.

**Comment by VladSoap** [comment]
"Может и чуть-меньше" - сказал бы я ,но я вспомнил что есть подводные локации

**Comment by EWENTOL** [comment]
Помимо адаптации под последнюю версию игры, разработчики могут также добавлять новые функции, например: авто активация испытания, доработку доведения электро фей, выполнение загадок с кубами и тп в инадзуме. Вообще идей еще много, все зависит от них. Но я, конечно, очень надеюсь на скорое обновление.

**Comment by VladSoap** [comment]
Решение загадок с кубами было бы слишком читерно как мне кажется.Авто испытания и электро-феи звучит довольно хорошо.Было бы неплохо ещё добавить тп к Аранарам,хотя это уже такое

**Comment by EWENTOL** [comment]
Да это я так, к слову). А так, функций и так множество, особенно бесплатно. Огромное им за это спасибо

**Comment by SecretLUL** [comment]
Я использую переводчик и перевел весь этот разговор, и я также очень надеюсь, что они опубликуют некоторые новые функции с новым обновлением. Я знаю, что в этом нет необходимости, так как они и так предоставляют нам много действительно интересных вещей бесплатно, что я очень ценю. Я очень надеюсь, что они будут продолжать свою работу вечно!

**Comment by QweRezOn** [comment]
Терпение... без него вы долго не протянете, все выйдет, но нужно время

**Comment by vaskakiller228** [comment]
> I am using a translation and have translated this conversation. I think that they should not deactivate the older versions, but simply let us use it. if some things do not work, then we wait for the main branch.


with new update in genshin, cheat will broken and it needs updating

**Comment by SIIIXLXRD** [comment]
> Решение загадок с кубами было бы слишком читерно как мне кажется.Авто испытания и электро-феи звучит довольно хорошо.Было бы неплохо ещё добавить тп к Аранарам,хотя это уже такое

Ну тп к аранарам есть уже как более полугода, а про электро-фей уже 2 года как и с обычными
