### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by kazuyabr** [Korepi/Korepi#66]
How can I participate for group discord cotton buds?
I want contribute with a code develop and translation for portuguese brazilian.

**Comment by tedddeptrai** [comment]
when korepi 4.0 released

**Comment by SecretLUL** [comment]
> when korepi 4.0 released

do you have any idea approximately when this will happen maybe?

**Comment by tedddeptrai** [comment]
> > when korepi 4.0 released
> 
> do you have any idea approximately when this will happen maybe?

nope

**Comment by kazuyabr** [comment]
I'm dev. Can I help develop?
I'm trying to join discord, but it says invites are paused =/ I want to contribute with development and translation.
