### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by Linnianci** [Korepi/Korepi#67]
I'm trying to join your discord channel, but it's closed for invites. Is there any way I can go about verifying my HWID, I really need your help, thanks.

**Comment by PlayAgainRL** [comment]
Same here

**Comment by QweRezOn** [comment]
> I'm trying to join your discord channel, but it's closed for invites. Is there any way I can go about verifying my HWID, I really need your help, thanks.


Alas, if the invitation is invalid, you will not be able to check the HWID in any other way.. while this is not possible, maybe something will be added and it can be done, or the invitations will be opened again, we need to hope for that...


If your question is resolved, please close the topic.
