### ISSUE TITLE
[Help] Don't know what happened

### ISSUE THREAD

**Issue by uhhhzedo** [Korepi/Korepi#80]
![image](https://github.com/Korepi/Korepi/assets/139381455/5da21230-ed4e-4472-a1e9-684f6e29a6a2)

I have just finished my 7 days login streak with micah bot today, but when I tab again into discord, i don't see myself in the Cotton Buds discord anymore. And when I try to join the server one more time, it said "unable to accept invite".

Here is my account:
![image](https://github.com/Korepi/Korepi/assets/139381455/09c10fae-0c13-45e6-a38e-e0505276f325)

**Comment by ghostdizz** [comment]
I also logged in for 7 days, and tried /getkey but soon I was kicked out of the server
I also tried to rejoin the server but can't
![image](https://github.com/Korepi/Korepi/assets/89640812/0d3a7120-482f-41e6-bbf6-0ff61cb2c224)
![image](https://github.com/Korepi/Korepi/assets/89640812/8e57e4f1-d263-4091-b655-3b08549fecef)

**Comment by Zangetsu6793** [comment]
Same

**Comment by QweRezOn** [comment]
> give me link discord pls

check main page https://github.com/Korepi/Korepi/
